changes

diff --git a/modules/conexao b/modules/conexao
--- a/modules/conexao
+++ b/modules/conexao
@@ -30,7 +30,7 @@ SCOLOR='\033[0m'
 			done
 			[[ -e $HOME/fim ]] && rm $HOME/fim && break
 			echo -e "\033[1;33m]"
-			sleep 1s
+			sleep 1
 			tput cuu1
 			tput dl1
 			echo -ne "\033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
@@ -46,7 +46,7 @@ SCOLOR='\033[0m'
 			svcs=$(echo -e "$PT" | grep -w "$pton" | awk '{print $1}' | uniq)
 			[[ "$porta" = "$pton" ]] && {
 				echo -e "\n\033[1;31mPORT \033[1;33m$porta \033[1;31mIN USE BY \033[1;37m$svcs\033[0m"
-				sleep 2
+				sleep 1
 				fun_conexao
 			}
 		done
@@ -56,42 +56,39 @@ SCOLOR='\033[0m'
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
 			echo -e "\E[44;1;37m              MANAGE  STUNNEL               \E[0m"
-			echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sslt"
+			echo -e "\n\033[1;33mPORT:\033[1;37m: \033[1;32m$sslt"
 			echo ""
 			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCHANGE PORT\033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mUNINSTALL STUNNEL\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mRETURN TO MAIN MENU\033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mUninstall\033[0m"
+			echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mMAIN MENU\033[0m"
 			echo ""
 			echo -ne "\033[1;32mchoose a number from the menu: "
-			read resposta
+			read menuChoice
 			echo ""
-			[[ "$resposta" = '1' ]] && {
-				echo -ne "\033[1;32mWHICH PORT YOU WANT TO USE ? "
+			[[ "$menuChoice" = '1' ]] && {
+				echo -ne "\033[1;32mEnter Port number: "
 				read porta
 				echo ""
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mInvalid port number, try again!"
-					sleep 2
+					sleep 1
 					clear
-					fun_conexao
+					inst_ssl
 				}
 				verif_ptrs $porta
-				echo -e "\033[1;32mCHANGING STUNNEL PORT ..."
+				echo -e "\033[1;32mCHANGING STUNNEL Listening PORT ..."
 				var2=$(grep 'accept' /etc/stunnel/stunnel.conf | awk '{print $NF}')
 				sed -i "s/\b$var2\b/$porta/g" /etc/stunnel/stunnel.conf >/dev/null 2>&1
-				echo ""
-				fun_bar 'sleep 2'
-				echo ""
-				echo -e "\033[1;32mRestarting STUNNEL!\n"
+				echo -e "\033[1;32mRestarting stunnel...\n"
 				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
 				echo ""
-				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mSUCCESSFULLY CHANGED PORT!" || echo -e "\033[1;31mUNEXPECTED ERROR!"
-				sleep 2s
+				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32msuccesful" || echo -e "\033[1;31mERROR!"
+				sleep 2
 				clear
 				fun_conexao
 			}
-			[[ "$resposta" = '2' ]] && {
+			[[ "$menuChoicev" = '2' ]] && {
 				echo -e "\033[1;32mUn-installing STUNNEL..."
 				del_ssl() {
 					service stunnel4 stop
@@ -106,53 +103,45 @@ SCOLOR='\033[0m'
 				fun_bar 'del_ssl'
 				echo ""
 				echo -e "\033[1;32mSTUNNEL REMOVED!"
-				sleep 3
+				sleep 1
 				fun_conexao
 			} || {
 				echo -e "\033[1;31mReturning to main menu...\033[0m"
-				sleep 3
+				sleep 1
 				fun_conexao
 			}
 		else
 			clear
 			echo -e "\E[44;1;37m              INSTALL STUNNEL               \E[0m"
 			echo ""
-			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALL STUNNEL (Port 22)\033[0m"
-			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALL STUNNEL (Port 80)\033[0m"
-			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mReturn\033[0m"
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALL STUNNEL\033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mmain menu\033[0m"
 			echo ""
 			echo -ne "\033[1;32mchoose a number from the menu: "
-			read resposta
+			read menuChoice
 			echo ""
-            if [[ "$resposta" = '1' ]]; then
-                portssl='22'
-            elif [[ "$resposta" = '2' ]]; then     
-                portssl='80'
-            elif [[ "$resposta" = '0' ]]; then
-				echo -e "\033[1;31mReturning to previous menu...\033[0m"
-				sleep 3
-				fun_conexao
-            else
-			echo ""
-			echo -e "\033[1;31mInvalid option !\033[0m"
-			sleep 1
-			inst_ssl
-		fi
-            clear
-			echo -e "\E[44;1;37m           STUNNEL INSTALLER             \E[0m"
-			echo ""
-			echo -ne "\033[1;32mDO YOU WISH TO Install Stunnel? \033[1;33m[y/n]:\033[1;37m "
-			read resposta
-			[[ "$resposta" = 'y' ]] && {
-				echo -ne "\n\033[1;33mCHOOSE A PORT FOR STUNNEL: \033[0m"
-        read porta
+            if [[ "$menuChoice" = '1' ]]; then
+                echo -ne "\n\033[1;33mForwarding Port(i.e 22): \033[0m"
+				read pssl
+				portssl="$pssl"
+				echo -ne "\n\033[1;33mIncoming port(i.e 443): \033[0m"
+        		read porta
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mInvalid port!"
-					sleep 3
+					sleep 2
 					clear
 					fun_conexao
 				}
+            elif [[ "$menuChoice" = '2' ]]; then
+				fun_conexao
+            else
+			echo ""
+			echo -e "\033[1;31mInvalid choice\033[0m"
+			sleep 1
+			inst_ssl
+			fi
+            clear
 				verif_ptrs $porta
 				echo -e "\n\033[1;32mINSTALLING STUNNEL...\033[1;33m"
 				echo ""
@@ -160,7 +149,7 @@ SCOLOR='\033[0m'
 				ssl_conf() {
 					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:$portssl\naccept = ${porta}" >/etc/stunnel/stunnel.conf
 				}
-				fun_bar 'ssl_conf'
+				ssl_conf
 				echo -e "\n\033[1;32mCREATING CERTIFICATE...\033[0m"
 				echo ""
 				ssl_certif() {
@@ -180,7 +169,7 @@ SCOLOR='\033[0m'
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
 					cd /etc/stunnel && wget https://raw.githubusercontent.com/matthew-0x/kangaroo_ssh/main/Sistema/script/stunnel.pem && cd $HOME
 				}
-				fun_bar 'ssl_certif'
+				ssl_certif
 				echo -e "\n\033[1;32mSTARTING STUNNEL !\033[0m"
 				echo ""
 				fun_finssl() {
@@ -189,13 +178,13 @@ SCOLOR='\033[0m'
 					/etc/init.d/stunnel4 restart
 				}
 				fun_bar 'fun_finssl' 'service stunnel4 restart'
-				echo -e "\n\033[1;32mSTUNNEL INSTALLED on PORT: \033[1;33m$porta\033[0m"
+				echo -e "\n\033[1;32mStunnel Listening on port: \033[1;33m$porta\033[0m"
 				sleep 2
 				clear
 				fun_conexao
-			} || {
+			|| {
 				echo -e "\n\033[1;31mReturning...\033[0m"
-				sleep 2
+				sleep 1
 				clear
 				fun_conexao
 			}
@@ -204,44 +193,41 @@ SCOLOR='\033[0m'
 
 	fun_openssh() {
 		clear
-		echo -e "\E[44;1;37m            OPENSSH             \E[0m\n"
+		echo -e "\E[44;1;37m            SSH             \E[0m\n"
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCHOOSE PORT\033[1;31m
 [\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVE PORT\033[1;31m
 [\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mReturn to main menu..\033[0m"
 		echo ""
 		echo -ne "\033[1;32mchoose a number from the menu: "
-		read resp
-		if [[ "$resp" = '1' ]]; then
+		read menuChoice
+		if [[ "$menuChoice" = '1' ]]; then
 			clear
-			echo -e "\E[44;1;37m         CHOOSE SSH PORT         \E[0m\n"
-			echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m "
+			echo -ne "\033[1;32mWHICH PORT?\033[1;37m "
 			read pt
 			[[ -z "$pt" ]] && {
 				echo -e "\n\033[1;31mInvalid Port!"
-				sleep 3
-				fun_conexao
+				sleep 2
+				fun_openssh
 			}
 			verif_ptrs $pt
-			echo -e "\n\033[1;32mAPPLYING CHOSEN SSH PORT\033[0m"
-			echo ""
 			fun_addpssh() {
 				echo "Port $pt" >>/etc/ssh/sshd_config
 				service ssh restart
 			}
 			fun_bar 'fun_addpssh'
-			echo -e "\n\033[1;32mPORT APPLIED SUCCESSFULLY\033[0m"
-			sleep 3
+			echo -e "\n\033[1;32mSSH Port Added.\033[0m"
+			sleep 1
 			fun_conexao
-		elif [[ "$resp" = '2' ]]; then
+		elif [[ "$menuChoice" = '2' ]]; then
 			clear
 			echo -e "\E[41;1;37m         REMOVE SSH PORT         \E[0m"
-			echo -e "\n\033[1;33mPORTS IN USE: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
-			echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO REMOVE\033[1;33m?\033[1;37m "
+			echo -e "\n\033[1;33mSSH Current ports: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)\n"
+			echo -ne "\033[1;32mWhich one to be removed?\033[1;33m?\033[1;37m "
 			read pt
 			[[ -z "$pt" ]] && {
 				echo -e "\n\033[1;31mInvalid Port!"
-				sleep 2
-				fun_conexao
+				sleep 1
+				fun_openssh
 			}
 			[[ $(grep -wc "$pt" '/etc/ssh/sshd_config') ]] && {
 				fun_delpssh() {
@@ -249,15 +235,15 @@ SCOLOR='\033[0m'
 					service ssh restart
 				}
 				fun_bar 'fun_delpssh'
-				echo -e "\n\033[1;32mPORT REMOVED SUCCESSFULLY\033[0m"
-				sleep 2
+				echo -e "\n\033[1;32mPORT REMOVED\033[0m"
+				sleep 1
 				fun_conexao
 			} || {
 				echo -e "\n\033[1;31mInvalid Port!"
-				sleep 2
-				fun_conexao
+				sleep 1
+				fun_openssh
 			}
-		elif [[ "$resp" = '3' ]]; then
+		elif [[ "$menuChoice" = '3' ]]; then
 			echo -e "\n\033[1;31mreturning.."
 			sleep 2
 			fun_conexao
@@ -274,8 +260,8 @@ SCOLOR='\033[0m'
 			echo -e "\E[44;1;37m             SSLH INSTALLER               \E[0m\n"
 			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mA PORT \033[1;37m443 \033[1;32mWILL BE USED BY STANDARD\033[0m\n"
 			echo -ne "\033[1;32mREALLY WANT TO INSTALL SSLH \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
-			read resp
-			[[ "$resp" = 's' ]] && {
+			read menuChoice
+			[[ "$menuChoice" = 's' ]] && {
 				verif_ptrs 443
 				fun_instsslh() {
 					[[ -e "/etc/stunnel/stunnel.conf" ]] && ptssl="$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)" || ptssl='3128'
@@ -329,7 +315,7 @@ SCOLOR='\033[0m'
 			echo -e "\033[1;32mSERVICE: \033[1;33mOPENSSH \033[1;32mPORT: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m♦ "
 
 			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
-				echo -e "\033[1;32mSERVICE: \033[1;33mSSL TUNNEL \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[1;32mSERVICE: \033[1;33mSTunnel \033[1;32mPORT: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts3="\033[1;32m♦ "
 			} || {
 				sts3="\033[1;31m○ "
@@ -337,11 +323,11 @@ SCOLOR='\033[0m'
 			
 			echo -e "\033[0;34m◇────────────────────────────────────────────────◇\033[0m"
 			echo ""
-			echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mOPENSSH $sts6\033[1;31m
-[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
-[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH (MULTIPLEXR) $sts7\033[1;31m
-[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mReturn to main menu \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
-[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mEXIT \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+			echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mSSH $sts6\033[1;31m
+[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mSTUNNEL $sts3\033[1;31m
+# [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH (MULTIPLEXR) $sts7\033[1;31m
+[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mReturn to main menu \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mExit Application \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo ""
 			echo -e "\033[0;34m◇────────────────────────────────────────────────◇\033[0m"
 			echo ""
@@ -354,27 +340,23 @@ SCOLOR='\033[0m'
 			1 | 01)
 				fun_openssh
 				;;
-			3 | 03)
-				fun_drop
-				;;
-			6 | 06)
+			2 | 02)
 				inst_ssl
-				;;
-		  8 | 08)
-				fun_chisel
-        ;;              
-			10)
+				;;   
+			3 | 03)
 				menu
 				;;
-			0 | 00)
+			4 | 04)
 				echo -e "\033[1;31mExiting application...\033[0m"
 				sleep 1
 				clear
 				exit
 				;;
 			*)
-				echo -e "\033[1;31mInvalid option !\033[0m"
-				sleep 2
+				echo -e "\033[1;31mInvalid choice!\033[0m"
+				sleep 1
+				clear
+				fun_conexao
 				;;
 			esac
 		done
